services:

  mongo:
    image: mongo:6.0
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    restart: no
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

  api:
    image: eurico149/marketcrud-api:latest
    restart: no
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://admin:admin123@mongo:27017/?authSource=admin}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-Nc/2vCmtlXcTNqY+ipCNp0DT6Gg}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-bKLIUw4cVhI6XyEJkhh030l3JaU}
      - URL_FRONTEND=${URL_FRONTEND:-http://localhost:8080}
    depends_on:
      - mongo
      - redis

  front:
    build: .
    restart: no
    depends_on:
      - api

  nginx:
    image: nginx:latest
    restart: no
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - api

volumes:
  mongo_data: